### ISSUE TITLE
package creation

### ISSUE THREAD

**Issue by lwaldron** [JonathanYe3/WebScraping_Microbiome#1]
This is great, @JonathanYe3! It's already useful enough that I would suggest converting this repo into a package format. You can use RStudio's method from https://support.rstudio.com/hc/en-us/articles/200486488-Developing-Packages-with-RStudio, or starting from a template with extra bells and whistles like https://github.com/seandavi/BuildABiocWorkshop2020 (like an automatically updating website, probably overkill but nice to learn about). Use roxygen2 for documentation (which these templates point you towards). 

However, I would recommend adding to the package a local copy of the first step of the scraped data and having that be a manual update, because too much scraping could result in being blocked by the site.

**Comment by JonathanYe3** [comment]
Thanks for reviewing Professor Waldron! I will get to work developing this script into a package, however, I am a bit unsure about what your second recommendation about a local copy of the first step of the scraped data means. I believe this means I should split up the scraping into separate batches and save those results locally, but could you please clarify for me?

Thanks, 

Jonathan

**Comment by lwaldron** [comment]
No problem! There are lots of ways you could do it, but one is [this example](https://github.com/waldronlab/HGNChelper/blob/master/update.sh) which has a script that updates a package data file in the `data/` directory and writes the date of update to the `inst/` directory. The `inst/` directory wherever the package is installed (as opposed to where you are developing it) can be accessed in code with the `system.file` function, which this package uses to print a message about when the data were last updated. The HGNChelper example provides the data as a documented data object exported by the package, so a user can see documentation of the data by doing `?hgnc.table` and load it into their environment by doing `data(hgnc.table)`.

**Comment by JonathanYe3** [comment]
Great, I will look into it and get started right away! Thank you for the help.
